Gmagent
meta-llama/llama-recipes pull request #805
Opened 2024-12-01 20:22 UTC by jeffxtang

# What does this PR do?

An app that shows how to build a Gmail agent app powered by Llama 3.1 8B running locally via Ollama, with custom tool calling natively supported in Llama 3.1. 

Fixes # (issue)

## Feature/Issue validation/testing

Please describe the tests that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [ ] Test A
Logs for Test A

- [ ] Test B
Logs for Test B

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/facebookresearch/llama-recipes/blob/main/CONTRIBUTING.md#pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes?  
- [ ] Did you write any new necessary tests?

Thanks for contributing 🎉!

2024-12-06 23:04 UTC, heyjustinai requested changes
i like this use case! can you also add a test plan in PR please (screen shot or video of the agent working)

2024-12-07 00:08 UTC, jeffxtang commented on recipes/use_cases/gmail_agent/README.md
> +* draft and send an email
The example command line inputs and outputs are in examples_log.txt

2024-12-07 00:13 UTC, jeffxtang commented
> i like this use case! can you also add a test plan in PR please (screen shot or video of the agent working)
Thanks for the review. Adding a test plan would be a bit too much work at this stage, but I'll add this task in the TODO. Yes some screenshots and demo video would be nice - will add them.

2024-12-07 00:56 UTC, jeffxtang commented on recipes/use_cases/gmail_agent/gmagent.py
> +def get_email_attachments(message_id, mime_type='application/pdf'):
Currently the app can only check for the default PDF attachments so if the user asks "do i have any word doc attachments larger than 5mb", the tool calling parameter will be "has:attachment filename:type:word larger:5mb" - more prompt engineering and pre-processing will be needed to handle this. For now I'll add another item in the TODO list.

2024-12-07 01:14 UTC, jeffxtang commented on recipes/use_cases/gmail_agent/main.py
> +    gmagent.set_email_service(args.user_email)
what parser_args already has error handling to make sure the email argument is provided - you mean to additionally check if the email entered is valid?

2024-12-07 01:19 UTC, jeffxtang commented on recipes/use_cases/gmail_agent/gmagent.py
> +    local_timezone = pytz.timezone("America/Los_Angeles")
good suggestion but the app is intended to show some real custom tool calling then the llama stack support and more advanced agent capabilities (multi-step reasoning and memory...) so i'll likely leave those few constants as is for now and will some come code refactoring in the future (or create such a class while adding more features).

2024-12-07 01:19 UTC, jeffxtang commented on recipes/use_cases/gmail_agent/gmagent.py
> +def list_emails(query='', max_results=100):
save as above. will do it in the future

2024-12-07 01:20 UTC, jeffxtang commented on recipes/use_cases/gmail_agent/gmagent.py
> +    def process_parts(parts):
agreed - but for now i'm trying to focus on agent specific implementation (have an item for attachment type handling in TODOs).

2024-12-07 02:13 UTC, jeffxtang commented on recipes/use_cases/gmail_agent/gmagent.py
> +def get_email_attachments(message_id, mime_type='application/pdf'):
added some screenshots (with emails masked - won't add a video demo for privacy reason:)

2024-12-09 23:31 UTC, heyjustinai commented on recipes/use_cases/gmail_agent/main.py
> +    gmagent.set_email_service(args.user_email)
I was thinking about adding error handling  to handle scenarios when it fails to connecting to Gmail API or saving token files - feel free to ignore if not applicable

2024-12-10 16:50 UTC, jeffxtang commented on recipes/use_cases/gmail_agent/main.py
> +    gmagent.set_email_service(args.user_email)
Ah if an incorrect token is entered and it fails to saving, an error "Malformed auth code" will now appear before exiting the program. 

When it fails to connecting to Gmail API (the only case I see is the missing of credentials.json file, described in README - but if the Gmail API service is down then typical network connection errors would occur), an error "No such file or directory: 'credentials.json'" will appear now.

2024-12-10 22:27 UTC, heyjustinai commented on recipes/use_cases/gmail_agent/main.py
> +    gmagent.set_email_service(args.user_email)
awesome, thanks for including these changes

2024-12-10 22:27 UTC, heyjustinai approved these changes

2024-12-16 22:41 UTC, merged